name: daily-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - devcard2.0
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@devcard2.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_message: "chore: update ${filename}"
